name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # INstall Node on the runner
      - name: Installing node.js
        uses: actions/setup-node@v3 # Used to install node environment - XXX https://github.com/actions/setup-node
        with:
          node-version: 18 # Use the same node.js version as the one Vercel's uses (currently node18.x)
          
      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults
      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run MinhaColecao.postman_collection.json -e MeuAmbiente.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html
      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults
